### PR TITLE
PR for fix of Issue #234 Crash in item completion

### PR DESCRIPTION
**Pull request by VNDPAL**
Whenever someone types in a command "System.Threading.Mutex(" the app crashes. because there is a Debug.Fail() is added. Just removing it fixes the issue.

### CODE REVIEW

**Comment by kindermannhubert** [comment]
Sorry, I don't believe this is correct solution. The assert is there for a reason and it's `Debug` one because it can continue in execution when it's not satisfied (as you found out).

We should instead find out what does `F:` prefix in `cref` variable in `CommentInnerBuilder.ParseCRef` mean. We already have exception for `!:` which means "invalid code reference" - unfortunately I don't remember where this I found out.

`cref` contains "F:System.Security.AccessControl.MutexRights.FullControl" - this type is from .NET Framework era and was removed in .NET Core 1.2 - that's the reason we're not able to find symbol for it.

**Comment by kindermannhubert** [comment]
Ok, `F:` isn't that special - it just means `field` 😀. I forgot.

This is from ECMA-334:
image

So I would just change behavior of `CommentInnerBuilder.ParseCRef` and remove this if:
image

That means "when we can't find the symbol we just use the cref text without highlighting".

**Comment by kindermannhubert** [comment]
Merged. Thanks.

**Comment by waf** [comment]
Thanks @VNDPAL! I've just added you to the [contributors list](https://github.com/waf/CSharpRepl/blob/main/CONTRIBUTING.md#csharprepl-contributors).

**Pull request merged**
